"""
llm_report.py
-------------
Generates an AI-assisted, human-readable radiology-style report from the
CNN's structured prediction output using an LLM (Anthropic Claude).

IMPORTANT: this module explicitly does NOT ask the LLM to diagnose from the
raw image. The image classification is done exclusively by the trained
CNN (deterministic, auditable, Grad-CAM-explainable). The LLM's job is
strictly report *writing and communication* from the CNN's already-computed
structured output -- turning a class + confidence + heatmap description
into a well-structured, appropriately hedged clinical-style narrative.
This separation of concerns keeps diagnostic responsibility with the
validated vision model and uses the LLM only for language generation.
"""

import os
from anthropic import Anthropic

MODEL_NAME = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-6")

SYSTEM_PROMPT = """You are a clinical documentation assistant supporting (not replacing) a \
radiologist. You are given the structured output of a validated deep-learning image \
classifier for a chest X-ray, including the predicted class, confidence score, and a \
description of which regions the model's Grad-CAM explainability method highlighted.

Write a concise, well-structured draft report with these sections:
1. AI Model Findings (state the predicted class and confidence plainly)
2. Region of Interest (explain, in plain language, what the Grad-CAM highlighted area suggests)
3. Clinical Interpretation Notes (what this finding pattern commonly corresponds to)
4. Recommended Next Steps (e.g., radiologist confirmation, follow-up imaging)
5. Disclaimer (mandatory, verbatim): "This report was generated by an AI system as a \
clinical decision-support draft only. It has not been reviewed by a licensed physician \
and must not be used as a sole basis for diagnosis or treatment."

Be factual, calibrated to the confidence score (hedge more when confidence is lower), \
and never state the finding as a certain diagnosis. Keep the total length under 250 words."""


def generate_report(predicted_class: str, confidence: float,
                     class_probabilities: dict, patient_note: str | None = None) -> str:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return _fallback_report(predicted_class, confidence, patient_note)

    client = Anthropic(api_key=api_key)

    probs_str = ", ".join(f"{k}: {v:.1%}" for k, v in class_probabilities.items())
    user_content = (
        f"Predicted class: {predicted_class}\n"
        f"Confidence: {confidence:.1%}\n"
        f"Full class probability distribution: {probs_str}\n"
        f"Grad-CAM highlighted region: localized area(s) of highest activation "
        f"contributing to the '{predicted_class}' prediction.\n"
    )
    if patient_note:
        user_content += f"Additional clinical context provided by requester: {patient_note}\n"

    try:
        message = client.messages.create(
            model=MODEL_NAME,
            max_tokens=600,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_content}],
        )
        text_blocks = [b.text for b in message.content if getattr(b, "type", None) == "text"]
        return "\n".join(text_blocks).strip() or _fallback_report(predicted_class, confidence, patient_note)
    except Exception as exc:  # network/auth/rate-limit errors shouldn't crash the API
        return _fallback_report(predicted_class, confidence, patient_note, error=str(exc))


def _fallback_report(predicted_class: str, confidence: float,
                      patient_note: str | None = None, error: str | None = None) -> str:
    """Deterministic template used when no ANTHROPIC_API_KEY is configured or the call fails."""
    note_line = f"\nClinical context provided: {patient_note}\n" if patient_note else ""
    err_line = f"\n[LLM call unavailable, using template fallback: {error}]\n" if error else ""
    return (
        f"AI MODEL FINDINGS\n"
        f"Predicted class: {predicted_class} (confidence: {confidence:.1%})\n"
        f"{note_line}"
        f"\nREGION OF INTEREST\n"
        f"Grad-CAM highlighted the image region(s) most responsible for this prediction; "
        f"see the accompanying heatmap overlay for exact localization.\n"
        f"\nCLINICAL INTERPRETATION NOTES\n"
        f"This finding pattern is consistent with the model's '{predicted_class}' class as "
        f"trained. Confidence below ~70% should be treated as inconclusive.\n"
        f"\nRECOMMENDED NEXT STEPS\n"
        f"Radiologist confirmation is recommended before any clinical action is taken.\n"
        f"{err_line}"
        f"\nDISCLAIMER\n"
        f"This report was generated by an AI system as a clinical decision-support draft "
        f"only. It has not been reviewed by a licensed physician and must not be used as a "
        f"sole basis for diagnosis or treatment."
    )
